### ISSUE TITLE
Introduce grades validation widget

### ISSUE THREAD

**Issue by kloudmm** [UTAS-HealthSciences/mylo-mate#106]
![image](https://user-images.githubusercontent.com/16098808/41443251-1ef70574-707f-11e8-9871-47646d24370e.png)

**Comment by kloudmm** [comment]
ClearGroups just needs to be cleaned up. 

1. Select Analyse Grades a second time and problems occur
2. Select Reset and it doesn't clean up properly, and see 1.

**Comment by connordeckers** [comment]
Should the reset button destroy the rendered graph?
