### ISSUE TITLE
Per Page indicator duplicate for Classlist and Enter Grades

### ISSUE THREAD

**Issue by kloudmm** [UTAS-HealthSciences/mylo-mate#120]
* In the Classlist and Enter Grades, could we possibly have a repeat of this doover at the top of the table?
* Let's right-align both (avoiding the up/down arrows)

![image](https://user-images.githubusercontent.com/16098808/42205339-8a5e6b88-7ee7-11e8-98bd-d4bedd88e97a.png)

**Comment by connordeckers** [comment]
Is already duplicated, but only when there's more than one page.

**Comment by connordeckers** [comment]
It has been requested that the pagination / `x per page` dropdown appear all the time, regardless of the existence of `Page x of x`. This should be achievable.

**Comment by connordeckers** [comment]
Also, bug: It floats _all the way_ to the right, which is off screen when the page is wide enough to scroll. Perhaps look into a fixed `x` pos?
