### ISSUE TITLE
Can't click on duplicated pagination controls

### ISSUE THREAD

**Issue by kloudmm** [UTAS-HealthSciences/mylo-mate#133]
![image](https://user-images.githubusercontent.com/16098808/42556549-48e904f8-852f-11e8-97bd-e639392a9f9b.png)
Waiting for confirmation this is Classlist or elsewhere.

**Comment by kloudmm** [comment]
Probably unrelated, but this happens on Enter Grades:
![slowclix](https://user-images.githubusercontent.com/16098808/42556699-c4a4efd0-852f-11e8-81de-384cbc5c1dd8.gif)

**Comment by kloudmm** [comment]
Confirmation the initial problem was on `Enter Grades`, only on wide pages. I can't see what would be blocking it, and it's not happening for me. Can you see if you can reproduce the issue?

**Comment by connordeckers** [comment]
Can't reproduce it at any size. May need to discuss with initial reporter.

**Comment by kloudmm** [comment]
I'm thinking this may be fixed now. Will re-open if not.
