### ISSUE TITLE
Rubric attached indicator in Assignment folders

### ISSUE THREAD

**Issue by connordeckers** [UTAS-HealthSciences/mylo-mate#139]
> Hiya, 
> 
> You know how assignment folders have the following useful little graphic indicators …    
![image](https://user-images.githubusercontent.com/9065239/42926037-848361da-8b73-11e8-9223-c4dd0fff3cf8.png)
> 
> I would really, really love one to tell me if there was a rubric attached to the box. At a glance. And maybe even if I could click on it, or hover, could it show the name? but hell that’s really wishful thinking. And icon would be great. (as opposed to the ‘R” that is already there for Restrictions) 
> 
> I could design one. 
> 
> Just putting it out there
>

**Comment by connordeckers** [comment]
Couple of style choices here:
1. R (for rubric) with a bit of bolding (Brons suggestion)
![image](https://user-images.githubusercontent.com/9065239/42926831-e517e97e-8b75-11e8-8621-063b335e2267.png)

2. D2L Rubric icon:
![image](https://user-images.githubusercontent.com/9065239/42926841-ecb29fd0-8b75-11e8-8b8e-a7f0299318c6.png)

Both would have title text.

**Comment by connordeckers** [comment]
Both options available in code block, one commented out. Try both for yourself and see which you prefer.
For reference, there are two assignments [in my Sandpit](https://mylo.utas.edu.au/d2l/lms/dropbox/admin/folders_manage.d2l?ou=190777), one which has a rubric attached. Feel free to use that space as a tester.

**Comment by kloudmm** [comment]
Added link in b361782, please test then close.
