### ISSUE TITLE
Semester - Year subtitle css needs adjustment for when long unit titles used

### ISSUE THREAD

**Issue by kloudmm** [UTAS-HealthSciences/mylo-mate#16]
See Scott's recent post. Ignore the bottom circle... Unless, what do you think, should we tweak that too? 
![image](https://user-images.githubusercontent.com/16098808/35788079-07cc8a4e-0a87-11e8-82d6-ed81f95abb55.png)

**Comment by connordeckers** [comment]
So the Semester - Year continues to appear, even without MyLO MATE even being active! It appears that this is part of the Daylight update you requested a while back. As such, we'll need to decide if it's worth logging a job for, and/or fixing it by replacing it with our own implementation.

![image](https://user-images.githubusercontent.com/9065239/35947539-6ec465e6-0cbc-11e8-812c-792028de1906.png)
