### ISSUE TITLE
Highlight by date - All Courses (pinnable) section

### ISSUE THREAD

**Issue by kloudmm** [UTAS-HealthSciences/mylo-mate#18]
Need to discuss the best way to do this.

**Comment by kloudmm** [comment]
Also add to `All Courses` page.

**Comment by kloudmm** [comment]
Confirm compatibility with OER too.

**Comment by connordeckers** [comment]
Search row colours don't persist throughout refreshes. This can be resolved by getting all of the current unit enrolments, instead of just the ones listed. Will take a few ms longer, but means we can persist them and apply the colours whenever the list changes, without running another API call.

**Comment by kloudmm** [comment]
Need to introduce to Advanced Search tool as well. This will be a separate issue.
