### ISSUE TITLE
[r][a] Only working in top discussion topics

### ISSUE THREAD

**Issue by kloudmm** [UTAS-HealthSciences/mylo-mate#22]
Looks like the querySelectors just need refining.

**Comment by kloudmm** [comment]
Also they disappear after filters are used.

**Comment by kloudmm** [comment]
These links are dropping in certain circumstances still. For example, I edited a topic, clicked Save, and it returned me to the main listing screen, and there were no [r][a] links. URI is something like https://mylo.utas.edu.au/d2l/le/239375/discussions/List?d2l_isfromtab=1

**Comment by connordeckers** [comment]
I think that in this case, the issue might have been with the URL checker. I forgot to put a wildcard at the end of the URL for the discussions, meaning that anything afterwards (e.g. `?d2l_isfromtab=1`) meant that it failed the check and didn't run the script. I've fixed this now, along with another URL that was forgotten.
