### ISSUE TITLE
Introduce background colour to indicate current unit status

### ISSUE THREAD

**Issue by kloudmm** [UTAS-HealthSciences/mylo-mate#24]
In the same way background colours are used to indicate unit status by date in unit lists, I'd like to do the same for the current unit, so at a glance people know whether the unit is open or not. I'm thinking about the best place to indicate this. Currently leaning towards a square or a dot to the right of the semester/year text unit the unit title, rather than changing the background colour. Discuss.

**Comment by connordeckers** [comment]
Commit 90e3c6d adds a coloured dot next to the title text, being: 
 - white (future)
 - green (current)
 - yellow/orange (exam period), or
 - red (old)

These are based upon the end-date of the unit, which is scraped from the API endpoint for that unit ID. 

![image](https://user-images.githubusercontent.com/9065239/36402777-004f4040-1635-11e8-8234-dc4c01428e17.png)
![image](https://user-images.githubusercontent.com/9065239/36402786-094cbdb2-1635-11e8-8186-7e1b5fdd048e.png)
![image](https://user-images.githubusercontent.com/9065239/36402787-0e8244d2-1635-11e8-8510-4fa643c72080.png)
![image](https://user-images.githubusercontent.com/9065239/36402793-1574b0cc-1635-11e8-9af4-ea37ff4828b5.png)

**Comment by connordeckers** [comment]
Side note: The last screenshot of the red dot, is actually correct. It's a unit with adjusted close dates ('deleted'). 

![image](https://user-images.githubusercontent.com/9065239/36402857-55266d1e-1635-11e8-8a53-b26a7a3da313.png)
