### ISSUE TITLE
Remove style tags in TinyMCE

### ISSUE THREAD

**Issue by connordeckers** [UTAS-HealthSciences/mylo-mate#29]
Bron has been manually removing style tags from the Code Edit function of TinyMCE panels, especially in Announcements. There's no reason this can't be a single button, especially given that it's a one-liner of code:
`tinymce.activeEditor.dom.doc.querySelectorAll('[style]').forEach(node => node.removeAttribute('style'));`

For starters, I'll put this directly into the Announcements Creator/Editor (two seperate URLs), but then we could investigate adding it directly to any TinyMCE editor found? Perhaps have the capacity for blacklisting editors?

**Comment by kloudmm** [comment]
Is this worth including as an option in the Edit HTML tool as well?

**Comment by connordeckers** [comment]
It could be looked into.

**Comment by kloudmm** [comment]
I found a need for this when I was fiddling with some Discussion descriptions today as well.

In terms of the Edit HTML tool, perhaps this could just be an enhancement to the Strip Tags command?

**Comment by connordeckers** [comment]
There is now a "Remove Style Attributes" button in the Edit HTML panel. This edits the text in the dialog only; it has no immediate effect on the HTML existing within the editor already. Effects are only applied when Save is pressed. 

Style tags are removed using RegEx (`/ style="[^]+?"/gmi`). This should be robust, but I haven't tested all possible implementations of how a style tag can be added. However, any _legitimate_ HTML markup (i.e. making sure there's no double quotes within the style tag) should be fine.
