### ISSUE TITLE
Bulk editing group names

### ISSUE THREAD

**Issue by kloudmm** [UTAS-HealthSciences/mylo-mate#53]
Investigate the potential of bulk editing group names (without POSTing using the API). To edit groups at the moment one has to click Groups, select the category, then one by one click on the group name to change it on a different screen. It would be great to be able to bulk edit all groups in a category on one screen. 

![image](https://user-images.githubusercontent.com/16098808/37747149-ddb1cfe4-2dd1-11e8-840a-8043846506bd.png)

**Comment by connordeckers** [comment]
This cannot be done without POSTing to the API.
