### ISSUE TITLE
Duplicated dots

### ISSUE THREAD

**Issue by kloudmm** [UTAS-HealthSciences/mylo-mate#55]
In events:
![image](https://user-images.githubusercontent.com/16098808/38484172-09fd668a-3c19-11e8-9877-69a71a09e4fe.png)

**Comment by connordeckers** [comment]
After some quick research, turns out that the second dot is a D2L specific dot! It's actually not related to our extension at all, as can be demonstrated by disabling MyLO MATE and refreshing the page. Tada!
