### ISSUE TITLE
Introduce 'in-place' ICB previews

### ISSUE THREAD

**Issue by kloudmm** [UTAS-HealthSciences/mylo-mate#65]
As discussed, pop it in place on hover. Let's see what happens.

**Comment by connordeckers** [comment]
In-place preview now appears in content editor.

When hovering over an item, the element will appear in the content editor, with a 'PREVIEW ONLY' heading above it, and overlaid with red angled stripes (seen below in screenshot). 
On mouseout, the item will be removed from the DOM. 

The preview element is marked as uneditable, using `contenteditable="false"`. This means that the user can change content *around* the preview, but not within.

![image](https://user-images.githubusercontent.com/9065239/39345731-7041ce8c-4a2d-11e8-922a-3787352f8fda.png)

**Comment by kloudmm** [comment]
Stellar work. Tried to break it, couldn't. Looks and functions really well.
