### ISSUE TITLE
Introduce a new Edit HTML button

### ISSUE THREAD

**Issue by kloudmm** [UTAS-HealthSciences/mylo-mate#71]
This should do exactly the same as the `Edit HTML` button at the bottom of the page. 
Here:
![image](https://user-images.githubusercontent.com/16098808/39416956-43569b0a-4c94-11e8-9f33-5903e371da0c.png)

**Comment by kloudmm** [comment]
Edit button appear at top of quizzes too

**Comment by connordeckers** [comment]
Can't reproduce in Quizzes or Surveys. Is it the Bulk edit link you're referencing? 
![image](https://user-images.githubusercontent.com/9065239/39555052-a70f5eee-4eb9-11e8-8ee8-655e367b05e1.png)
