### ISSUE TITLE
Discussion progress indication

### ISSUE THREAD

**Issue by kloudmm** [UTAS-HealthSciences/mylo-mate#80]
While this is working, it would be good to include either (ideally) a progress bar, or a loading animation that catches the eye, so staff know things are happening. Easy to miss the grey text.

**Comment by connordeckers** [comment]
There is currently no way to find a total post count, meaning that we can't display an accurate progress meter. A PIE item has been created to resolve this (https://desire2learn.brightidea.com/ideas/D4581). In the interim, a loading circle will be placed next to the "Messages loading" text, and the text will be made a little more visible.
