### ISSUE TITLE
Add assignment folder status totals - part 2

### ISSUE THREAD

**Issue by kloudmm** [UTAS-HealthSciences/mylo-mate#85]
Part 1 is per page. Part 2 is to investigate API calls to provide per folder totals.

**Comment by connordeckers** [comment]
Looked into the API; there is no clear definition of what is 'Draft Saved' vs 'Published', etc. Even if we iterate over all the submissions, there's little guarantee of getting the information we need. We'll close this and put it on hold for now. If the API improves, we may revisit this in future.
