### ISSUE TITLE
Search a unit for text

### ISSUE THREAD

**Issue by connordeckers** [UTAS-HealthSciences/mylo-mate#98]
Mentioned by someone, it's not currently possible (to my knowledge) to search a unit for text, and show matching results. 

Something that could be done with our extension as a unit homepage widget, perhaps?

**Comment by kloudmm** [comment]
Need to escape the search text. E.g. search for a backslash for the following error:

> Uncaught (in promise) SyntaxError: Invalid regular expression: /\/: \ at end of pattern
>     at new RegExp (<anonymous>)
>     at search (SearchUnit.widget.js:91)

**Comment by kloudmm** [comment]
`This widget will search the current unit for the text provided.` change to `Search the current unit for:`. Change placeholder text to `Search text`.

**Comment by kloudmm** [comment]
- Introduce minimum search text length. Searching for a single character takes too long. IndexOf v RegEx?
- Move `Search Unit` button above the results so they don't have to scroll down to click in case they want to perform a second search

**Comment by kloudmm** [comment]
,d2l-link causes long titles to behave annoyingly.

**Comment by kloudmm** [comment]
I got an out of memory message when doing a test search. Can you please check resources are being disposed of and memory released correctly? I would have thought the browser itself would do this automatically...

**Comment by kloudmm** [comment]
Dodgy Word document causing search to fail?

```
SearchUnit.widget.js:65 Uncaught (in promise) TypeError: Cannot read property 'async' of undefined
    at Object.DOCX (SearchUnit.widget.js:65)
DOCX @ SearchUnit.widget.js:65
async function (async)
Promise @ SearchUnit.widget.js:83
Promise.all.files.map.file @ SearchUnit.widget.js:83
search @ SearchUnit.widget.js:83
async function (async)
search @ SearchUnit.widget.js:33
```

**Comment by kloudmm** [comment]
Add checkboxes allowing case sensitivity and RegEx.

**Comment by connordeckers** [comment]
Still have yet to reproduce the issue of running out of memory. If I can reproduce it, I will attempt to fix it.

**Comment by kloudmm** [comment]
Introduce `\\[search]\\mi` prefix and suffix to text box which toggles if they select Regex, and the `i` appears only if they select Regex and case sensitive.

**Comment by kloudmm** [comment]
Correct `/i` appendage (at the moment it shows `/i` when `Case sensitive` is selected).

**Comment by kloudmm** [comment]
Check initial state of `/i`:
![initialstate](https://user-images.githubusercontent.com/16098808/42790135-a62ee5d4-89ac-11e8-8a9d-d15ea205a06e.gif)

**Comment by kloudmm** [comment]
Let's have the search iterate through the content titles as well. All of them. Links, discussions, everything. Just the titles as listed in the Content. And... maybe the descriptions as well if they're easy to get at - I haven't checked the API for this.
