### ISSUE TITLE
Ignore browsehappy links in our link checker widget

### ISSUE THREAD

**Issue by connordeckers** [UTAS-HealthSciences/mylo-mate#99]
Whilst they're not false positives, it can be hard for staff to remove the links when they don't render on the page, and it can help clean up the link checker error list.

Perhaps, for the desperate few, we could allow them to be checked based on a flag in the options (disabled by default)? Meaning that for those who intentionally want to find the bad browsehappy links, they can.

**Comment by kloudmm** [comment]
Yes, let’s make it optional. I would like it to flag them as broken by default, though.
